[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; 串口监视器与上传速率配置
monitor_speed = 115200
upload_speed = 115200

; 编译选项
build_flags = 
    -DCORE_DEBUG_LEVEL=1

; 默认分区表配置（使用 huge_app 解决 WiFi + BLE 的 Flash 溢出问题）
board_build.partitions = huge_app.csv

; 上传与调试协议配置
upload_protocol = esptool
monitor_filters = direct

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3
